# Learn Numpy

Numpy is multidimentional array library. Why use Numpy array instead of list?

Numpy
* Fixed Type
* Fast
* Require less memory
* No checking element's type
* Data stored is right next to each other (Contiguous Memory)
* Effective cache utilization

List
* Slow
* Require more memory
* Check element you are looking at of what type it is
* Data stored is scattered around in the memory


## Source

https://www.youtube.com/watch?v=GB9ByFAIAH4&t=1136s

##  0. Import libraries

In [2]:
import numpy as np
import sys

In [3]:
# # List multiplication is not possible, this will cause an error
# a = [1, 3, 5]
# b = [2, 4, 6]

# print(a*b)

In [4]:
# Numpy array multiplication is possible
a = np.array([1, 3, 5])
b = np.array([2, 4, 6])

print(a*b)

[ 2 12 30]


## 1. The Basics

In [5]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [6]:
b = np.array([[2.0, 4.0, 5.1], [2.6, 7.3, 9.8]])

print(b)

[[2.  4.  5.1]
 [2.6 7.3 9.8]]


In [7]:
# Get dimension
print(a.ndim)
print(b.ndim)

1
2


In [8]:
# Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [9]:
# Get type
print(a.dtype)
print(b.dtype)

int16
float64


In [10]:
# Get size (in memory byte) for each element in the array
print(a.itemsize)
print(b.itemsize)

2
8


In [11]:
# Get number of element in the array
print(a.size)
print(b.size)

3
6


In [12]:
# Get size (in memory byte) for an array
print(a.nbytes)
print(b.nbytes)

6
48


## 2. Accessing/changing specific elements, rows, columns, etc.

In [16]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
# Get a specific element [r ,c], index start from 0
a[0, 5]

6

In [20]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [22]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [23]:
# Change element value
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [24]:
# Change element value
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [25]:
# 3d example
b = np.array([ [[1,2],[3,4]], [[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
# Get a specific element (work outside in)
b[0, 1, 1]

4

In [27]:
# Get a specific element (work outside in)
b[0, :, :]

array([[1, 2],
       [3, 4]])

## 3. Initializing different types of arrays

In [32]:
# ZEROS
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
# ONES
np.ones((4,2,2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [34]:
# Any other number
np.full((2,2), 99) # (row, col), number

array([[99, 99],
       [99, 99]])

In [36]:
# Any other number (full_like) using the shape of other array
a = np.array([1,2,3,4,5])
print("a:", a)

b = np.full_like(a,4)
print("b:", b)

a: [1 2 3 4 5]
b: [4 4 4 4 4]


In [40]:
# Random decimal number
np.random.rand(4,2) # remember that the shape DO NOT need one more ()

array([[0.00734107, 0.57575475],
       [0.84847957, 0.96179626],
       [0.49672445, 0.62046245],
       [0.56283112, 0.3853036 ]])

In [41]:
# Random decimal number with shape of a
np.random.random_sample(a.shape)

array([0.26349294, 0.30257551, 0.2966771 , 0.78597429, 0.16879492])

In [44]:
# Random integer valuess
np.random.randint(-3, 7, size=(3,3)) # (min, max+1, size)

array([[-1,  5, -3],
       [ 1, -2, -1],
       [ 0, -3,  3]])

In [45]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
# Repeat array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


## 4. Challenge: Initialize this vector

<img src="soal1.PNG" width="300">

In [55]:
k = np.ones((5,5), dtype='int32')
print(k)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [59]:
k[1:4,1:4]=np.zeros((3,3))
k[2,2]=9

In [60]:
print(k)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## 5. Be careful when copying arrays

In [63]:
a = np.array([1,2,3])
b = a
b[0] = 100

## Noted that when we change b, a is also affected 
print("b:", b)
print("a:", a)

b: [100   2   3]
a: [100   2   3]


In [64]:
# To avoid copying problem, use .copy
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

## Noted that when we change b, a is also affected 
print("b:", b)
print("a:", a)

b: [100   2   3]
a: [1 2 3]


## 6. Mathematics

In [68]:
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [69]:
# +2 for every element
a+2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [70]:
# *2 for every element
a*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [73]:
# Sum of array
a = np.array([1,2,3,4])
b = np.array([2,2,2,2])

a+b

array([3, 4, 5, 6])

In [74]:
# Power
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [77]:
# Take the sin or cos
print("sin(a):", np.sin(a))
print("cos(a):", np.cos(a))

sin(a): [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
cos(a): [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


## 7. Linear Algebra

In [80]:
# Matrix multiplication
a = np.ones((2,3))
b = np.full((3,2),2)

print("a:", a)
print("b:", b)

print("a * b: ", np.matmul(a,b))

a: [[1. 1. 1.]
 [1. 1. 1.]]
b: [[2 2]
 [2 2]
 [2 2]]
a * b:  [[6. 6.]
 [6. 6.]]


In [81]:
# Find determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [83]:
# # More:
# inverse
# eigenvalues
# matrix norms
# singular vector decomposition
# etc..

## 8. Statistics

In [84]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
np.min(stats)

array([1, 2, 3])

In [86]:
np.max(stats)

6

In [91]:
np.sum(stats, axis=1)

array([ 6, 15])

## 9. Reorganizing arrays

In [98]:
# Reshape
before = np.array([[1,2,3,4],[5,6,7,8]])
print("before:\n", before)
print("\n")

after = before.reshape((2,2,2))
print("after:\n", after)

before:
 [[1 2 3 4]
 [5 6 7 8]]


after:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [100]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [101]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## 10. Miscellaneous

### 10.A. Load data from file

In [106]:
# Load data from file
data1 = np.genfromtxt('data.txt', delimiter=',')
data1

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [104]:
data1.shape

(3, 18)

In [110]:
data1=data1.astype('int')

In [111]:
data1.dtype

dtype('int32')

In [112]:
data1

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

### 10.B. Boolean masking and advanced indexing

In [113]:
data1 > 5

array([[False,  True,  True,  True,  True,  True, False, False,  True,
         True,  True,  True, False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True, False,  True,  True,
        False, False, False, False,  True,  True, False,  True,  True],
       [False,  True,  True,  True,  True,  True, False, False,  True,
        False, False, False,  True,  True,  True, False,  True,  True]])

In [114]:
# get data1 value where value>5
data1[data1>5]

array([ 13,  21,  11, 196,  75,  34,   6,   7,   8,  42,  12,  33, 766,
        75,  55,   6,   6,   7,  11,  12,  22,  33,  11, 999,  11,  78,
         9,   8,   7,  76,  88])

In [115]:
## You can index with a list in numpy
a = np.array([43, 35, 37, 29, 64, 51, 38])
a[[0, 2, 4]]

array([43, 37, 64])

In [116]:
# Check whether there is any value>50, for each column
np.any(data1>50, axis =0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [117]:
# Check whether all values>50, for each column
np.all(data1>50, axis =0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [118]:
# Check value between 50 and 100
((data1>50) & (data1<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

## 11. Index this matrix

* Soal a: biru
* Soal b: hijau
* Soal c: merah

<img src="soal2.PNG" width="600">

In [122]:
matrix = []

for i in range(1,31):
    matrix.append(i)

#print(matrix)

matrix_arr = np.array(matrix)
matrix_arr = matrix_arr.reshape(6,5)

print(matrix_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [123]:
# Soal biru
index_matrix = matrix_arr[2:4, 0:2]
index_matrix

array([[11, 12],
       [16, 17]])

In [125]:
# Soal hijau
index_matrix = matrix_arr[[0,1,2,3], [1, 2, 3, 4]]
index_matrix

array([ 2,  8, 14, 20])

In [127]:
# Soal merah
index_matrix = matrix_arr[[0,4,5], 3:]
index_matrix

array([[ 4,  5],
       [24, 25],
       [29, 30]])